# Generated by Django 2.2 on 2021-11-13 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ba_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
