# Generated by Django 2.2 on 2021-11-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ba_app', '0002_auto_20211112_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lastName',
        ),
    ]
